<?php
/**
 * Template for sharing wishlist for logged in user
 */
$customer      = Mage::getSingleton( 'customer/session' )->getCustomer();
$email         = $this->getEnteredData( 'email' ) ? $this->getEnteredData( 'email' ) : $customer->getEmail();
$wishlist      = Mage::getModel( 'wishlist/wishlist' )->loadByCustomer( $customer, true );
$wishListItems = $this->getGuestWishlist();
$_helper       = $this->helper( 'js_guestwishlist' );
?>
<div class="container">
    <div class="page-title">
        <h1>Share Your Award Idea List</h1>
    </div><?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getUrl( 'guest-wishlist/share/send' ); ?>" id="form-validate-share" method="post"
          class="wishlist-form">
        <div class="form-group">
			<?php echo $this->getBlockHtml( 'formkey' ) ?>
            <p class="required"><?php echo $this->__( '* Required Fields' ) ?></p>
            <div class="row">
                <div class="col-md-6">
                    <label for="full_name" class="required"><em>*</em><?php echo $this->__( 'Your name' ) ?></label>
                    <div class="input-box">
                        <input type="text" name="full_name" id="full_name"
                               class="form-control required-entry input-text"
                               value="<?php echo $this->getEnteredData( 'full_name' ) ?>"/>
                    </div>
                </div>
                <div class="col-md-6">
                    <label for="email" class="required"><em>*</em><?php echo $this->__( 'Your email address' ) ?>
                    </label>
                    <div class="input-box">
                        <input type="text" name="personal_email" id="email"
                               class="form-control required-entry input-text validate-email"
                               value="<?php echo $email; ?>"/>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label for="recipient_name" class="required">Recipient Name</label>
                    <div class="input-box">
                        <input type="text" name="recipient_name" id="recipient_name"
                               class="form-control required-entry input-text" value="">
                    </div>
                </div>
                <div class="col-md-6">
                    <label for="email_address" class="required"><em>*</em>Email addresses, separated by commas</label>
                    <div class="input-box">
                        <input type="text" name="emails" id="email_address"
                               class="form-control required-entry input-text" value="">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 padding-fix">
                    <div class="input-box wishlist-checkbox">
                        <label for="cc_myself">Cc: Myself</label>
                        <input type="checkbox" name="cc_myself" id="cc_myself" value="1" checked="checked">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="message">Message</label>
                <div class="input-box">
                    <textarea id="wishlist-message" name="message" class="form-control" cols="60"
                              rows="5"><?php echo $_helper->getDefaultShareMessage(); ?></textarea>
                </div>
            </div>
        </div>
        <div class="buttons-set form-buttons">
            <button type="submit" title="Email Award Idea List" class="button" id="wishlistfrm"><span><span>Email Award Idea List</span></span>
            </button>
        </div>
    </form>

    <h3>My Award Idea List</h3>
	<?php if ( count( $wishListItems ) ): ?>
        <ul class="wishlist-list wishlist-share row">
			<?php foreach ( $wishListItems as $wishlistItem ): ?>
				<?php $_product = Mage::getModel( 'catalog/product' )->load( $wishlistItem->getProductId() ); ?>
                <li class="col-md-3 col-sm-6 col-xs-6 product-container item">
                    <a class="product-image" href="<?php echo $this->getProductUrl( $_product ); ?>"
                       title="<?php echo $this->escapeHtml( $_product->getName() ) ?>">
                        <img src="https://image.crystal-d.com/img/u245-y/jpg/<?php echo $_product->getMainProductImage(); ?>">
                    </a>
                    <div class="main-price medium mt-10">
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           class="list-name dark-grey"><?php echo $_product->getShortDescription(); ?></a>
                        <div class="items light-grey">Item <span>#<?php echo $_product->getSku(); ?></span></div>
                        <div class="list-price light-grey"><?php echo $this->helper( 'js_product' )->getRetailPriceRange( $_product ); ?></div>
                    </div>
                    <div class="actions">
                        <a href="<?php echo $this->getItemRemoveUrl( $wishlistItem ); ?>" title="Remove Item"
                           class="btn-wishlist-remove_link"><span>Remove</span></a>
                    </div>
                </li>
			<?php endforeach; ?>
        </ul>
	<?php else: ?>
        You have no items in your Award Idea List.
	<?php endif; ?>
</div><!-- Close containter for wishlist items -->
<script type="text/javascript">
  //<![CDATA[
  Validation.addAllThese([
    ['validate-emails', '<?php echo Mage::helper( 'core' )->jsQuoteEscape( $this->__( 'Please enter a valid email addresses, separated by commas. For example johndoe@domain.com, johnsmith@domain.com.' ) ) ?>', function (v) {
      if (Validation.get('IsEmpty').test(v)) {
        return true;
      }

      var valid_regexp = /^[a-z0-9\._-]{1,30}@([a-z0-9_-]{1,30}\.){1,5}[a-z]{2,4}$/i;
      var emails = v.split(',');

      for (var i = 0; i < emails.length; i++) {
        if (!valid_regexp.test(emails[i].strip())) {
          return false;
        }
      }

      return true;
    }]
  ]);
  var dataForm = new VarienForm('form-validate-share', true);
  //]]>
</script>