<?php
$hint = str_replace('"', '\"' , htmlspecialchars(trim($this->getField()->getHint())));
$fieldCode = $this->getField()->getCode();

$value = htmlspecialchars($this->getFieldValue());
if($fieldCode == 'product_sku') {
	$value = Mage::registry('product')->getSku();
}
?>



<?php // var_dump( ); ?>
<input id='<?php echo $this->getFieldId() ?>'
       type='text'
       name='<?php echo $this->getFieldName() ?>'
       class='<?php echo $this->getFieldClass() ?>'
       style='<?php echo $this->getFieldStyle() ?>'
       placeholder="<?php echo $hint?>"
       value='<?php echo $value ?>'
       <?php if ($this->getField()->getType() == 'email'){ ?>onkeyup="if(this.value.search(' ')>=0){this.value = this.value.replace(' ','');}"<?php } ?>
       <?php if ($this->getField()->getDisabled()) { ?> disabled <?php } ?>
/>