<?php
$_configHelper = Mage::helper('searchautocomplete/config');
$_product      = $this->getItem();
$_resource = Mage::getSingleton('catalog/product')->getResource();

$mainProductImage = $_resource->getAttributeRawValue($_product->getId(), 'main_product_image', Mage::app()->getStore());
$shortDescription = $_resource->getAttributeRawValue($_product->getId(), 'short_description', Mage::app()->getStore());
$retailPrice = $_resource->getAttributeRawValue($_product->getId(), 'retailprice1', Mage::app()->getStore());
$netPrice = $_resource->getAttributeRawValue($_product->getId(), 'netprice1', Mage::app()->getStore());
$trophyPrice = $_resource->getAttributeRawValue($_product->getId(), 'trophyblankprice1', Mage::app()->getStore());

$groupId = Mage::getSingleton('customer/session')->getCustomerGroupId();
$qty = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty();
?>
<li data-url="<?php echo $_product->getProductUrl() ?>">
    <?php if ($_configHelper->isShowImage()): ?>
    <div class="searchautocomlete-image">
	    <img alt="<?php echo htmlspecialchars($shortDescription); ?>" class="" src="http://image.crystal-d.com/img/u494-y/jpg/<?php echo $mainProductImage; ?>.jpg" width="<?php echo $_configHelper->getImageWidth() ?>px" height="<?php echo $_configHelper->getImageHeight() ?>px"/>
    </div>
    <?php endif ?>
    <a class="name highlight" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>

    <?php if ($_configHelper->isShowRating()): ?>
        <?php $_reviewSummary = $_configHelper->getReviewSummary($_product->getId()); ?>
        <?php if ($_reviewSummary->getReviewsCount() > 0) : ?>
        <div class="ratings">
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $_reviewSummary->getRatingSummary() ?>%"></div>
            </div>
            <span class="reviews"><?php echo $_reviewSummary->getReviewsCount() ?> Review(s)</span>
        </div>
        <?php endif ?>
    <?php endif ?>

    <?php if ($_configHelper->isShowShortDescription()): ?>
        <div class="highlight">
        <?php echo Mage::helper('core/string')->truncate(strip_tags($this->getProductShortDescription($_product)), $_configHelper->getShortDescriptionLen()) ?>
        </div>
    <?php endif ?>
    <?php if ($_configHelper->isShowPrice()): ?>
        <?php echo $this->getPriceHtml($_product, false) ?>
        <div class="clearfix"></div>
    <?php endif ?>

	<div class="search-info-box">
		<div class="highlight search-info">
			Item #: <?php echo $_product->getSku(); ?>
		</div>
	</div>
</li>