<div class="pager col-md-8">
    <div class="count-container">
        <?php if($this->getLastPageNum()>1): ?>
            <p class="amount amount--has-pages">
                <?php echo $this->__('%s-%s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            </p>
        <?php else: ?>
            <p class="amount amount--no-pages">
                <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
            </p>
        <?php endif; ?>

        <div class="limiter">
            <label><?php echo $this->__('Show') ?></label>
            <select onchange="setLocation(this.value)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Results per page')); ?>">
            <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                    <?php echo $_limit ?>
                </option>
            <?php endforeach; ?>
            </select>
        </div>
    </div>
</div>
<div class="pager col-md-4 pager-bottom-wrapper hidden">
    <div class="right"><?php echo $this->getPagerHtml() ?></div>
</div>