<?php
/**
 * #usedOnepageTemplate
 */
?>
<?php
/**
 * One page checkout payment methods
 *
 * @var $this Mage_Checkout_Block_Onepage_Payment_Methods
 */
?>

<?php
$methods = $this->getMethods();
$oneMethod = count($methods) <= 1;
$customerId = Mage::getSingleton('customer/session')->getCustomer()->getId();
$hasTerms = Mage::getSingleton('customer/customer')->load($customerId)->getData('has_terms');
?>
<?php if (empty($methods)): ?>
    <dt>
        <?php echo $this->__('No Payment Methods') ?>
    </dt>
<?php else:
    foreach ($methods as $_method): $_code = $_method->getCode();?>
		<?php if ($_code != 'payroll'): ?>
        <?php if($_code == 'terms' && $hasTerms != 'yes'): ?>
            <?php continue; ?>
        <?php endif; ?>
		    <dt id="dt_method_<?php echo $_code ?>">
                <?php if (!$oneMethod): ?>
                    <input id="p_method_<?php echo $_code ?>"
                        value="<?php echo $_code ?>" type="radio" name="payment[method]"
                        title="<?php echo $this->escapeHtml($_method->getTitle()) ?>"
                        onclick="payment.switchMethod('<?php echo $_code ?>')"
                        <?php if ($this->getSelectedMethodCode() == $_code): ?>
                            checked="checked"
                        <?php endif;?>
                        class="radio" />
                <?php else: ?>
                    <span class="no-display">
                        <input id="p_method_<?php echo $_code ?>"
                            value="<?php echo $_code ?>" type="radio" name="payment[method]"
                            checked="checked" class="radio" />
                    </span>
                    <?php $oneMethod = $_code;?>
                <?php endif; ?>
                <label for="p_method_<?php echo $_code ?>">
                    <?php echo $this->escapeHtml($this->getMethodTitle($_method)) ?>
                    <?php echo $this->getMethodLabelAfterHtml($_method) ?>
                </label>
            </dt>
        <?php endif;?>
        <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
            <dd id="dd_method_<?php echo $_code ?>">
                <?php echo $html; ?>
            </dd>
        <?php endif;?>
    <?php endforeach; ?>
<?php endif; ?>
<?php echo $this->getChildChildHtml('additional'); ?>
<script type="text/javascript">
    //<![CDATA[
    <?php echo $this->getChildChildHtml('scripts'); ?>
    payment.init();
    <?php if (is_string($oneMethod)): ?>
    payment.switchMethod('<?php echo $oneMethod ?>');
        <?php endif;?>

    var radios = document.getElementsByName('payment[method]');
    for( var x = 0; x < radios.length; x++ ){
        radios[x].addEventListener('click', function(){
            document.fire('mgw:adjustHeightToDiv');
        });
    }
    //]]>
</script>
