<header class="cd-car__header <?php echo 'cd-car__header--'.$cTheme . ' ' . 'cd-car__header--'.$cStyle  ?>">

  <?php
    if($cHL){

      $hlParts = explode('|', $cHL, 2);
      $hlParts = array_map('trim', $hlParts);
      
    ?>

      <h2 class="cd-car__headline <?php echo 'cd-car__headline--'.$cTheme . ' ' . 'cd-car__headline--'.$cStyle  ?>">
        <?php
          if(count($hlParts) >= 2){
            echo "<span>{$hlParts[0]} </span><span>{$hlParts[1]}</span>";
          }else{
            echo trim($cHL);
          }
        ?>
      </h2>

    <?php }

    if($cSHL){ ?>

      <span class="cd-car__subheadline <?php echo 'cd-car__subheadline--'.$cTheme . ' ' . 'cd-car__subheadline--'.$cStyle  ?>">
        <?php echo trim($cSHL); ?>
      </span>

    <?php }

    if($cBod){ ?>

      <div class="cd-car__body <?php echo 'cd-car__body--'.$cTheme . ' ' . 'cd-car__body--'.$cStyle  ?>">
        <?php echo trim($cBod); ?>
      </div>

    <?php }

    if($cLink || $cVideo){ ?>

      <div class="cd-car__cta <?php echo 'cd-car__cta--'.$cTheme . ' ' . 'cd-car__cta--'.$cStyle  ?>">

        <?php if($cLink){ ?>

          <a class="cd-car__cta__button <?php echo 'cd-car__cta__button--'.$cTheme . ' ' . 'cd-car__cta__button--'.$cStyle  ?>" href="<?php echo $cLink; ?>">
            <span>
              <?php echo $cCta ? $cCta : 'Click Here'; ?>
            </span>
          </a>
          
        <?php }

        if($cVideo){ ?>

          <button type="button" class="cd-car__cta__button <?php echo 'cd-car__cta__button--'.$cTheme . ' ' . 'cd-car__cta__button--'.$cStyle  ?>" onclick="vidModal('<?php echo $cVideo; ?>')">
            <span>
              Watch Video
            </span>
          </button>

        <?php } ?>

      </div>

    <?php } ?>

</header>