<div class="row main-container">
			<div class="col-md-12" style="text-align: center;">
				<div class="mw-overlay-wrapper">
					<h1 class="mw-textsize1" style="color: white;">Welcome, <?php echo $name; ?>!</h1>
					<h2 class="mw-textsize3" style="color: white; margin-bottom: 24px; font-weight: 400;">
						Experience the best site for purchasing blank crystal awards.</h2>
					<div>
						<a class="mw-textsize2 btn btn-lg mw-overlay-btn"
							href="https://ot.crystal-d.com/scripts/ajax/door/open_door.php?email=<?php echo $email ?>&key=<?php echo $key ?>"  
							target="_blank">
							TRACK MY ORDERS
						</a>
						<a class="mw-textsize2 btn btn-lg mw-overlay-btn"
							title="Corporate Gifts" href="/products?cat=44" target="_self">
							SHOP AWARDS &amp; GIFTS
						</a>
					</div>
				</div>
				<img title="Blank Crystal Awards" alt="Blank Crystal Awards" src="<?php echo Mage::getBaseUrl(); ?>/media/wysiwyg/Dashboard/Blank-Slider2.png" />
			</div>
			<div style="text-align: center;">&nbsp;</div>
			<div style="text-align: center;">
				<div class="row">
					<div class="col-md-6">
						<a title="Shop All Awards" href="/ordering-blanks" target="_self">
							<img title="Free Shipping on Blank Orders over $400
								with Ground Shipping in the 48 contiguous states" alt="Free
								Shipping on Blank Orders over $400 with Ground Shipping in the
								48 contiguous states"
								src="<?php echo Mage::getBaseUrl(); ?>/media/wysiwyg/Dashboard/Free-Shipping2.jpg"/>
						</a>
					</div>
					<div class="col-md-6">
					<div>
						<iframe src="https://www.youtube.com/embed/j5AeIk0W8Lo" class="mw-iframe" width="800" height="450"
							allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
							frameborder="0"></iframe>
					</div>
				</div>
				</div>
				<div class="col-md-12">
					<h2 style="text-align: center;">
						<span style="font-size: xx-large;">Shop Blanks by Category</span>
					</h2>
					<p>&nbsp;</p>
				</div>
				<div class="row squish-row">
					<div class="col-md-3"><a title="Optical Crystal Awards"
							href="/products?cat=41" target="_self"><img title="Optical Crystal
								Awards" alt="Optical Crystal Awards"
								src="<?php echo Mage::getBaseUrl(); ?>/media/wysiwyg/Dashboard/Pristine2.jpg"
								/></a>
						<p><a title="Optical Crystal Awards" href="/products?cat=41"
								target="_self">Pristine</a></p>
					</div>
					<div class="col-md-3"><a title="Star Awards" href="/products?cat=72"
							target="_self"><img title="Star Awards" alt="Star Awards"
								src="<?php echo Mage::getBaseUrl(); ?>/media/wysiwyg/Dashboard/Star1.jpg"
								/></a>
						<p><a title="Star Awards" href="/products?cat=72" target="_self">Star</a></p>
					</div>
					<div class="col-md-3"><a title="Art Glass Awards" href="/products?cat=164"
							target="_self"><img title="Art Glass Awards" alt="Art Glass Awards"
								src="<?php echo Mage::getBaseUrl(); ?>/media/wysiwyg/Dashboard/Art-Glass1.jpg"
								/></a>
						<p><a title="Art Glass Awards" href="/products?cat=164" target="_self">Art
								Glass</a></p>
					</div>
					<div class="col-md-3">
						<a title="Goal-Setter Awards" href="/products?cat=154" target="_self">
							<img title="Goal-Setter Awards" alt="Goal-Setter Awards"
								src="<?php echo Mage::getBaseUrl(); ?>/media/wysiwyg/Dashboard/Goal-Setter1.jpg"/>
						</a>
						<p>
							<a title="Goal-Setter Awards" href="/products?cat=154" target="_self">Goal-Setter</a>
						</p>
						<p>&nbsp;</p>
					</div>
				</div>
				<div class="col-md-12" style="text-align: center;">
					<div class="mw-overlay-wrapper">
						<h2 class="mw-textsize3" style="color: white;">EXCEPTIONAL. FLAWLESS.</h2>
						<h1 class="mw-textsize1" style="color: white;">Corporate Gifts</h1>
						<h2 class="mw-textsize3" style="color: white; margin-bottom: 24px; font-weight: 400;">
							Just one click away!</h2>
						<div>
							<a class="mw-textsize2 btn btn-lg mw-overlay-btn"
								title="Corporate Gifts" href="/products?cat=44" target="_self">
								SEARCH NOW
							</a>
						</div>
					</div>
					<img title="Corporate Gifts" alt="Corporate Gifts"
						src="<?php echo Mage::getBaseUrl(); ?>/media/wysiwyg/Dashboard/Corporate-Gifts.jpg"/>
				</div>
				<div class="col-md-12" style="text-align: center;">&nbsp;</div>
				<div class="col-md-12" style="text-align: center;">&nbsp;</div>
				<div class="col-md-12">
				<div class="col-md-6">
					<h2 style="text-align: center;">&nbsp;<span style="color: #7987a0;">Product Application: 3D Subsurface</span></h2>
						<iframe frameborder="0" class="mw-iframe" height="450" width="800"
							src="https://www.youtube.com/embed/fNDjr19pk-A"></iframe>
				</div>
				<div class="col-md-6">
					<h2 style="text-align: center;">&nbsp;<span style="color: #7987a0;">45 Award Ideas in 100 Seconds</span></h2>
						<iframe frameborder="0" class="mw-iframe" height="450" width="800"
							src="https://www.youtube.com/embed/NK01uVXFdqc"></iframe>
				</div>
				<div class="col-md-12" style="text-align: center;">&nbsp;</div>
				<div class="col-md-12" style="text-align: center;">&nbsp;</div>
				<div class="col-md-12" style="text-align: center;">
					<div class="mw-overlay-wrapper">
						<h2 class="mw-textsize3" style="color: white;">GET MORE WOW FOR LESS WITH</h2>
						<h1 class="mw-textsize1" style="color: white;">FREE shipping on blank orders over $400</h1>
						<h2 class="mw-textsize3" style="color: white; margin-bottom: 24px; font-weight: 400;">
							via ground in the 48 contiguous states.</h2>
						<div>
							<a class="mw-textsize2 btn btn-lg mw-overlay-btn"
							title="Shop All Awards" href="/products" target="_self">
								SHOP NOW!
							</a>
						</div>
					</div>
					<img title="Free Shipping on Blank
						Orders over $400 with Ground Shipping in the 48 contiguous
						states" alt="Free Shipping on Blank Orders over $400 with Ground
						Shipping in the 48 contiguous states"
						src="<?php echo Mage::getBaseUrl(); ?>/media/wysiwyg/Dashboard/Free-Ship.jpg"/>
				</div>
			</div>
		</div>