<?php

/**

 * NeoTheme Austrlia (Neo Industries Pty Ltd)

 *

 * NOTICE OF LICENSE

 *

 * This source file is subject to Neo Industries Pty LTD Non-Distributable Software Modification License (NDSML)

 * that is bundled with this package in the file LICENSE.txt.

 * It is also available through the world-wide-web at this URL:

 * http://www.neotheme.com.au/legal/licenses/NDSM.html

 * If the license is not included with the package or for any other reason, 

 * you did not receive your licence please send an email to 

 * license@neotheme.com.au so we can send you a copy immediately.

 *

 * This software comes with no warrenty of any kind. By Using this software, the user agrees to hold 

 * Neo Industries Pty Ltd harmless of any damage it may cause.

 *

 * @category    modules

 * @module      NeoTheme_ImageRotator

 * @copyright   Copyright (c) 2011 Neo Industries Pty Ltd (http://www.neotheme.com.au)

 * @license     http://www.neotheme.com.au/  Non-Distributable Software Modification License(NDSML 1.0)

 */

/**

 * @see NeoTheme_Blog_Block_Post_Summary

 */

 $formatType = Mage::getStoreConfig(NeoTheme_Blog_Helper_Data::XPATH_CONFIG_DATETIME_FORMAT_TYPE);

 $format = ($formatType != 'custom')?

    Mage::app()->getLocale()->getDateTimeFormat($formatType): 

    Mage::getStoreConfig(NeoTheme_Blog_Helper_Data::XPATH_CONFIG_DATETIME_CUSTOM_FORMAT);

	$image_name= $this->getPost()->getBlogImage();

	$photonew = substr($image_name,25);
	$imageUrl = Mage::getBaseDir('media').DS."neotheme_blog".DS."neotheme_blog";

// path of the resized image to be saved
// here, the resized image is saved in media/resized folder
$imageResized =     Mage::getBaseDir('media').DS."neotheme_blog".DS."neotheme_blog".DS."resized".DS.$photonew;

// resize image only if the image file exists and the resized image file doesn't exist
// the image is resized proportionally with the width/height 135px
$media_url=Mage::getBaseUrl('media');
$newImageUrl = Mage::getBaseUrl('media').$image_name;
?>

<?php /*?>	<article class="post">   
	<h2><a href="<?php echo $this->getPost()->getReadMoreUrl(); ?>"><?php echo $this->getPost()->getTitle()?></a></h2>
    

    

    <div class="post-summary">
		
		<?php if(!empty($image_name)){?>
		<div class="col-md-12">
			<div class="col-md-2"><a href="<?php echo $this->getPost()->getReadMoreUrl(); ?>"><img src="<?php echo $newImageUrl;?>" style="width:125px;height:125px"></a></div>
			<div class="col-md-10">
			
			<div class="post-metadata">

        <div class="post-time">

            <?php echo $this->__('Posted On: ');?> 

            <?php $date = ($this->getPost()->getPostDate() != NULL)? $this->getPost()->getPostDate()  : $this->getPost()->getCreatedAt() ; ?>

            <?php  //echo Mage::app()->getLocale()->date($date)->toString($format); ?>
			<?php echo date("F j, Y",strtotime($this->getPost()->getPostDate())); ?>

            <?php // $timestamp = (int) Mage::app()->getLocale()->date($date)->getTimestamp() ;?>

            <?php // echo date('d D', $timestamp)?><?php // echo date('M', $timestamp)?>

        </div>

        <?php if ($authorName = $this->getPost()->getAuthor()) :?>

        <div class="post-author"><?php echo $this->__('by'); ?> <?php echo $authorName; ?></div>

        <?php endif;?>

    </div>
			<?php echo $this->getPost()->getSummary(); ?> <div class="read-more"><a href="<?php echo $this->getPost()->getReadMoreUrl(); ?>"><?php echo $this->__($this->getPost()->getReadMoreText()); ?></a></div>
              <!--- For Post Category-->
        <div class="post-info">

	<?php if ( (int) $this->getPost()->getStatus() == NeoTheme_Blog_Model_Post::STATUS_DRAFT) : ?>

        	<h3 style="color:red;"><?php //echo $this->__('[Draft] (not visible publicly)');?></h3>

        <?php endif; ?>

        

        <?php if ($this->getPost()->getCategories()->count() > 0):?>

        <ul class="post-categories">

            <?php echo $this->__('Posted In: ');?>

            <?php $i = 0; ?>

            <?php foreach($this->getPost()->getCategories() as $category):?>

                <?php //$catName =  ($i > 0)? ',' . $category->getName() : $category->getName(); ?>
				<?php $catName .=  ($i > 0)? '<li><a href="'.$category->getListUrl().'">,&nbsp;' . $category->getName().'</a></li>' : '<li><a href="'.$category->getListUrl().'">' . $category->getName().'</a></li>'; ?>

                 <!--   <li><a href="<?php echo $category->getListUrl();?>"><?php echo $catName; ?></a></li>-->

                <?php $i++; ?>

            <?php endforeach; ?>
			<?php echo $catName;?>
        </ul>

        <?php endif; ?>

        <?php if ( Mage::helper('neotheme_blog')->isDefaultCommentingEnabled()) : ?>

        <?php 

         $commentCount = $this->getPost()->getComments()->count();

         $commentText =  ($commentCount == 1) ? $this->__("comment"):$this->__("comments");

        ?>

        <ul>

            <li class="post-comments"><?php echo $commentCount; ?> <?php echo $commentText;?></li>

        </ul>

        <?php endif; ?>

    </div>
            
            </div>
		
		</div>
		<?php } else {?>
        <div class="post-metadata">

        <div class="post-time">

            <?php echo $this->__('Posted On: ');?> 

            <?php $date = ($this->getPost()->getPostDate() != NULL)? $this->getPost()->getPostDate()  : $this->getPost()->getCreatedAt() ; ?>

            <?php  //echo Mage::app()->getLocale()->date($date)->toString($format); ?>
			<?php echo date("F j, Y",strtotime($this->getPost()->getPostDate())); ?>

            <?php // $timestamp = (int) Mage::app()->getLocale()->date($date)->getTimestamp() ;?>

            <?php // echo date('d D', $timestamp)?><?php // echo date('M', $timestamp)?>

        </div>

        <?php if ($authorName = $this->getPost()->getAuthor()) :?>

        <div class="post-author"><?php echo $this->__('by'); ?> <?php echo $authorName; ?></div>

        <?php endif;?>

    </div>
		<?php echo $this->getPost()->getSummary();
		?>
        <div class="read-more"><a href="<?php echo $this->getPost()->getReadMoreUrl(); ?>"><?php echo $this->__($this->getPost()->getReadMoreText()); ?></a>
        
        </div>
        <!--- For Post Category-->
        <div class="post-info">

	<?php if ( (int) $this->getPost()->getStatus() == NeoTheme_Blog_Model_Post::STATUS_DRAFT) : ?>

        	<h3 style="color:red;"><?php //echo $this->__('[Draft] (not visible publicly)');?></h3>

        <?php endif; ?>

        

        <?php if ($this->getPost()->getCategories()->count() > 0):?>

        <ul class="post-categories">

            <?php echo $this->__('Posted In: ');?>

            <?php $i = 0; ?>

            <?php foreach($this->getPost()->getCategories() as $category):?>

                <?php //$catName =  ($i > 0)? ',' . $category->getName() : $category->getName(); ?>
				<?php $catName .=  ($i > 0)? '<li><a href="'.$category->getListUrl().'">,&nbsp;' . $category->getName().'</a></li>' : '<li><a href="'.$category->getListUrl().'">' . $category->getName().'</a></li>'; ?>

                 <!--   <li><a href="<?php echo $category->getListUrl();?>"><?php echo $catName; ?></a></li>-->

                <?php $i++; ?>

            <?php endforeach; ?>
			<?php echo $catName;?>
        </ul>

        <?php endif; ?>

        <?php if ( Mage::helper('neotheme_blog')->isDefaultCommentingEnabled()) : ?>

        <?php 

         $commentCount = $this->getPost()->getComments()->count();

         $commentText =  ($commentCount == 1) ? $this->__("comment"):$this->__("comments");

        ?>

        <ul>

            <li class="post-comments"><?php echo $commentCount; ?> <?php echo $commentText;?></li>

        </ul>

        <?php endif; ?>

    </div>
        <?php
		 }?>
		
        

    </div>

    

    

    

    <div class="clr"></div>

</article><?php */?>
<?php
///social_share('mailto:?subject=Balancing+Practice+and+School+Work&body=http%3A%2F%2Ffscamps.com%2Fblog%2Fbalancing-practice-and-school-work%2F');

$blog_title=$this->getPost()->getTitle();
$blog_url=$this->getPost()->getReadMoreUrl();
?>
<ul class="share-single type-single five">
<li>

<a class="facebook hooked" href="javascript:popWin('https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($blog_url); ?>&t=<?php echo urlencode($blog_url); ?>', 'facebook', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo $this->__('Share on Facebook') ?>">Facebook</a>
</li>
<li>

<a class="twitter hooked" href="javascript:popWin('http://twitter.com/home/?status=<?php echo urlencode($blog_title . ' (' . $blog_url . ')'); ?>', 'twitter', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo $this->__('Share on Twitter') ?>">Twitter</a>
</li>
<li>

<a class="email hooked" href="javascript:popWin('mailto:?subject=<?php echo $blog_title; ?>&body=<?php echo urlencode($blog_url); ?>',  'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo $this->__('Message') ?>">Message</a>
</li>
<li>
<a class="linkedin hooked" href="https://www.linkedin.com/company/crystal-d" title="<?php echo $this->__('Linked In') ?>" target="_blank">Linked In</a>
</li>
<li>

<a class="gplus hooked" href="javascript:popWin('https://plus.google.com/share?url=<?php echo urlencode($blog_url); ?>', 'google', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo $this->__('Google Plus') ?>">Google Plus</a>
</li>
</ul>


<?php $date = ($this->getPost()->getPostDate() != NULL)? $this->getPost()->getPostDate()  : $this->getPost()->getCreatedAt() ; ?>
<?php $blogdates= date("F j, Y",strtotime($this->getPost()->getPostDate())); ?>


			

<div class="blog-image"><a href="<?php echo $this->getPost()->getReadMoreUrl(); ?>"><img src="<?php echo $newImageUrl;?>" alt="blog_image" /></a></div>
<div class="blog-title"><h2><a href="<?php echo $this->getPost()->getReadMoreUrl(); ?>"><?php echo $this->getPost()->getTitle()?></a></h2></div>
<div class="blog-readmore"><a href="<?php echo $this->getPost()->getReadMoreUrl(); ?>">Read More</a>
<span class="post_date"></span></div>

<script>
//alert('222');
jQuery('.breadcrumb li:last a').removeAttr('href');

if(jQuery('.breadcrumb li:nth-child(3) a').text() == 'Blog') {
 jQuery('.breadcrumb li:nth-child(3) a').text('Crystal D Blog');
}


</script>
<style>
.blog article.post .post-info ul.post-categories {
    float: left;
}
.blog article.post .post-info .post-categories li {
    display: inline;
}
.blog article.post {
    border-bottom: 1px solid #efefef;
    margin-bottom: 20px;
    padding-bottom: 10px;
}

.blog article.post .post-info li.post-comments {
    float: right;
}
.blog article.post .post-metadata {
    padding: 10px 0;
}
.share-single {
  background-color: rgba(255, 255, 255, 0.9);
  bottom: 55px !important;
  box-sizing: border-box;
  display: block;
  height: 40px !important;
  margin: 0 6% !important;
  opacity: 0;
  padding: 0 !important;
  position: absolute !important;
  transition: opacity 0.15s linear 0s;
  width: 88% !important;
  list-style:none;
}
.share-single, .share-item.type-single {
  z-index: 7;
}
.share-single li {
  background: #fff none repeat scroll 0 0 !important;
  border-color: #eee #eee #eee white !important;
  border-style: solid !important;
  border-width: 1px !important;
  box-shadow: none !important;
  box-sizing: border-box;
  display: block !important;
  float: left !important;
  height: 100% !important;
  margin: 0 !important;
  padding: 0 !important;
  text-indent: -9999px !important;
  width: 20% !important;
}
.share-single li:first-child {
  border-left: 1px solid #eee !important;
}
.share-single li:last-child {
  border-right: 1px solid #eee !important;
}
.share-single li a {
  display: block !important;
  height: 100% !important;
  text-indent: -9999px !important;
}
.share-single li a.facebook {
  background: rgba(0, 0, 0, 0) url("<?php echo $media_url?>/social/button-facebook.png") no-repeat scroll center 0;
}
.share-single li a.twitter {
  background: rgba(0, 0, 0, 0) url("<?php echo $media_url?>/social/button-twitter.png") no-repeat scroll center 0;
}
.share-single li a.email {
  background: rgba(0, 0, 0, 0) url("<?php echo $media_url?>/social/button-email.png?v=c23476a88282") no-repeat scroll center 0;
}
.share-single li a.linkedin {
  background: rgba(0, 0, 0, 0) url("<?php echo $media_url?>/social/button-linkedin.png?v=b0dd1d95b619") no-repeat scroll center 0;
}
.share-single li a.gplus {
  background: rgba(0, 0, 0, 0) url("<?php echo $media_url?>/social/button-gplus.png?v=99e69d55b485") no-repeat scroll center 0;
}
.share-single li a.facebook:hover {
  background-position: center -40px;
}
.share-single li a.twitter:hover {
  background-position: center -40px;
}
.share-single li a.email:hover {
  background-position: center -40px;
}
.share-single li a.linkedin:hover {
  background-position: center -40px;
}
.share-single li a.gplus:hover {
  background-position: center -40px;
}
ul.custom-blog  li:hover .share-single {
  opacity: 1;
}
.custom-blog .blog-readmore::after {
  background: transparent url("<?php echo $media_url?>/social/sprite-1x.png") no-repeat scroll left top;
  content: "";
  display: block;
  height: 16px;
  position: absolute;
  right: 17px;
  top: 13px;
  width: 16px;
}
ul.custom-blog  li:hover .blog-readmore::after{
  background-position: -16px 0;
}
</style>