<script>
  new Splide('#carousel__<?php echo $cRandId ?>', {
    type: 'loop',
    gap: '16px',
    mediaQuery: 'min',
    breakpoints: {
      0: {
        perPage: 1
      },
      768: {
        perPage: <?php echo $cNum > 1 ? 2 : 1; ?>
      },
      1024: {
        perPage: <?php echo $cNum > 1 ? 3 : 1; ?>
      },
      1280: {
        perPage: <?php echo $cNum; ?>
      }
    }
  }).mount();
</script>