<?php
//#usedOnepageTemplate
/** @var Mage_Checkout_Block_Onepage_Billing $this */
?>
<h1>Billing Information</h1>
<form id="co-billing-form" action="">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <div style="padding: 20px 20px;">
        <p><em>*</em>PO Number</p>
        <div class="input-box">
            <input type='text' 
                name='custom[ponumber]' 
                class="input-text required-entry" 
                value='<?php echo $this->getQuote()->getData('ponumber'); ?>'
                />
        </div>
    </div>
    <div class="flex-twoColumn">
        <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />

        <!-- First Name -->
        <div class="text-left">
            <label for="billing:firstname" class="required">
                <em>*</em><?php echo $this->__('First Name') ?>
            </label>
            <input type="text" 
                id="billing:firstname" 
                name="billing[firstname]" 
                value="<?php echo $this->escapeHtml($this->getAddress()->getFirstname()) ?>" 
                title="<?php echo Mage::helper('core')->quoteEscape($this->__('First Name')) ?>" 
                class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('firstname') ?>" 
                />
        </div>

        <!-- Middle Name -->
        <div class="text-left">
            <label for="billing:middlename">
                <?php echo $this->__('Middle Name/Initial') ?>
            </label>
            <input type="text"
                id="billing:middlename"
                name="billing[middlename]" 
                value="<?php echo $this->escapeHtml($this->getAddress()->getMiddlename()) ?>" 
                title="<?php echo Mage::helper('core')->quoteEscape($this->__('Middle Name/Initial')) ?>" 
                class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('middlename') ?>" 
                />
        </div>

        <!-- Last Name -->
        <div class="text-left">
            <label for="billing:lastname" class="required">
                <em>*</em><?php echo $this->__('Last Name') ?>
            </label>
            <input type="text"
                id="billing:lastname"
                name="billing[lastname]" 
                value="<?php echo $this->escapeHtml($this->getAddress()->getLastname()) ?>" 
                title="<?php echo Mage::helper('core')->quoteEscape($this->__('Last Name')) ?>" 
                class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('lastname') ?>" 
                />
        </div>

         <!-- Company -->
         <div class="text-left" style="display: none;">
            <label for="billing:company">
                <?php echo $this->__('Company') ?>
            </label>
            <input type="text" 
                id="billing:company" 
                name="billing[company]" 
                value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" 
                title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>" 
                class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" 
                />
        </div>

        <!--Address line 1-->
        <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
        <div class="text-left">
            <label for="billing:street1" class="required">
                <em>*</em><?php echo $this->__('Address') ?>
            </label>
            <input type="text" 
                id="billing:street1" 
                name="billing[street][]"
                value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" 
                title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" 
                class="input-text <?php echo $_streetValidationClass; ?>" 
                />
        </div>

        <!-- Address Line 2 -->
        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        <div class="text-left">
            <label for="billing:street2">
                <?php echo $this->__('Address 2') ?>
            </label>
            <input type="text" 
                id="billing:street2"
                name="billing[street][]"
                value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(2)) ?>" 
                title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address 2')) ?>" 
                class="input-text <?php echo $_streetValidationClass ?>" 
                />
        </div>

        <!-- City -->
        <div class="text-left">
            <label for="billing:city" class="required">
                <em>*</em><?php echo $this->__('City') ?>
            </label>
            <input type="text" 
                id="billing:city" 
                name="billing[city]" 
                value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" 
                title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" 
                class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" 
                />
        </div>

        <!-- State/ Province -->
        <div class="text-left">
            <label for="billing:region" class="required">
                <em>*</em><?php echo $this->__('State/Province') ?>
            </label>
            <select id="billing:region_id" 
                name="billing[region_id]" 
                title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" 
                class="validate-select" 
                style="display:none;">
                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
            </select>
            <script type="text/javascript">
            //<![CDATA[
                $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
            //]]>
            </script>
            <input type="text" 
                id="billing:region" 
                name="billing[region]" 
                value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" 
                title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" 
                class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" 
                style="display:none;" />
        </div>

        <!-- zip/Postal Code-->
        <div class="text-left">
        <label for="billing:postcode" class="required">
            <em>*</em><?php echo $this->__('Zip/Postal Code') ?>
        </label>
        <input type="text" 
            id="billing:postcode" 
            name="billing[postcode]" 
            value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" 
            title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" 
            class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" 
            />
        </div>

        <!-- Country -->
        <div class="text-left">
            <label for="billing:country_id" class="required">
                <em>*</em><?php echo $this->__('Country') ?>
            </label>
            <?php echo $this->getCountryHtmlSelect('billing') ?>
        </div>
        
        <!-- Telephone -->
        <div class="text-left">
            <label for="billing:telephone" class="required">
                <em>*</em><?php echo $this->__('Telephone') ?>
            </label>
            <input type="tel" 
                id="billing:telephone" 
                name="billing[telephone]" 
                value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" 
                title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" 
                class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" 
                />
        </div>
    </div>
    
  
    <div class="buttons-set" id="billing-buttons-container">
        <button type="button" 
            title="<?php echo $this->quoteEscape($this->__('Continue')) ?>" 
            class="btn checkoutStep-btn" onclick="billing.save()">
            <span><span><?php echo $this->__('Take Me to My Payment Information!') ?></span></span>
        </button>
        <span class="please-wait" id="billing-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" 
                alt="<?php echo $this->quoteEscape($this->__('Loading next step...')) ?>" 
                title="<?php echo $this->quoteEscape($this->__('Loading next step...')) ?>" 
                class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>

</form>
<script type="text/javascript">
//<![CDATA[
    var billing = new Billing(
        'co-billing-form', 
        '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', 
        '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
    var billingForm = new VarienForm('co-billing-form');

    //billingForm.setElementsRelation('billing:country_id', 'billing:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->jsQuoteEscape($this->__('Select State/Province...')) ?>');
    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);

    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 
        'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
    if ($('onepage-guest-register-button')) {
        Event.observe($('onepage-guest-register-button'), 'click', function(event) {
            var billingRememberMe = $('co-billing-form').select('#remember-me-box');
            if (billingRememberMe.length > 0) {
                if ($('login:guest') && $('login:guest').checked) {
                    billingRememberMe[0].hide();
                } else if ($('login:register') && ($('login:register').checked || $('login:register').type == 'hidden')) {
                    billingRememberMe[0].show();
                }
            }
        });
    }
//]]>
</script>
