<div class="text-center" style="max-width: 1206px; margin: 0 auto;">
<div class="page-title">
    <h1><?php echo $this->__('Your Order Has Been Placed!') ?></h1>
</div>
<div class="text-gray">Thank you for your purchase! We're getting your order ready to be shipped. Be on the lookout for an email when it has shipped or log into your Order Tracker account to see the progress. If something comes up and you need immediate assistance, please contact us at <a href="mailto:blanks@crystal-d.com">blanks@crystal-d.com</a> or 866-925-3301.
</div>
<iframe width="847" height="466" src="https://www.youtube.com/embed/FbgyXoQ1Vpk" 
    frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" 
    allowfullscreen="" style="width: 847px; height: 466px; max-height: 440px; max-width: 780px; margin: 25px 0;"></iframe>
<div class="buttons-set">
    <button type="button" class="btn checkoutStep-btn" 
    title="<?php echo Mage::helper('core')->quoteEscape($this->__('Continue Shopping')) ?>" 
    onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>
</div>
