<?php
/**
 * #usedOnePage
 * This is a helper for displaying discounts and prices.
 */
?>
<?php /* ?>
<tr>
    <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
            <?php echo $this->escapeHtml($this->getTotal()->getTitle()); ?>
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
    </td>
    <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
            <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
    </td>
</tr>
< */ ?>
<p class="table-p">
    <span><?php echo $this->escapeHtml($this->getTotal()->getTitle()); ?>:</span>
    <span><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()); ?></span>
</p>
